#include <gdk/gdkkeysyms.h>

#include "telnetp.h"

#define MOD_NONE 0x0
#define MOD_SHIFT 0x1
#define MOD_CTRL 0x2
#define MOD_ALT 0x4

static struct {
	int type;
	int mod;
	char *key;
	int gdk_mod;
} ansi_p_code_map[] = {
	{PCODE_F1, MOD_NONE, "F1", GDK_F1},
    {PCODE_F1_SHIFT, MOD_SHIFT, "Shift F1", GDK_F1},
    {PCODE_F1_CTRL, MOD_CTRL, "Control F1", GDK_F1},
    {PCODE_F1_ALT, MOD_ALT, "Alt F1", GDK_F1},
    {PCODE_F2, MOD_NONE, "F2", GDK_F2},
    {PCODE_F2_SHIFT, MOD_SHIFT, "Shift F2", GDK_F2},
    {PCODE_F2_CTRL, MOD_CTRL, "Control F2", GDK_F2},
    {PCODE_F2_ALT, MOD_ALT, "Alt F2", GDK_F2},
    {PCODE_F3, MOD_NONE, "F3", GDK_F3},
    {PCODE_F3_SHIFT, MOD_SHIFT, "Shift F3", GDK_F3},
    {PCODE_F3_CTRL, MOD_CTRL, "Control F3", GDK_F3},
    {PCODE_F3_ALT, MOD_ALT, "Alt F3", GDK_F3},
    {PCODE_F4, MOD_NONE, "F4", GDK_F4},
    {PCODE_F4_SHIFT, MOD_SHIFT, "Shift F4", GDK_F4},
    {PCODE_F4_CTRL, MOD_CTRL, "Control F4", GDK_F4},
    {PCODE_F4_ALT, MOD_ALT, "Alt F4", GDK_F4},
    {PCODE_F5, MOD_NONE, "F5", GDK_F5},
    {PCODE_F5_SHIFT, MOD_SHIFT, "Shift F5", GDK_F5},
    {PCODE_F5_CTRL, MOD_CTRL, "Control F5", GDK_F5},
    {PCODE_F5_ALT, MOD_ALT, "Alt F5", GDK_F5},
    {PCODE_F6, MOD_NONE, "F6", GDK_F6},
    {PCODE_F6_SHIFT, MOD_SHIFT, "Shift F6", GDK_F6},
    {PCODE_F6_CTRL, MOD_CTRL, "Control F6", GDK_F6},
    {PCODE_F6_ALT, MOD_ALT, "Alt F6", GDK_F6},
    {PCODE_F7, MOD_NONE, "F7", GDK_F7},
    {PCODE_F7_SHIFT, MOD_SHIFT, "Shift F7", GDK_F7},
    {PCODE_F7_CTRL, MOD_CTRL, "Control F7", GDK_F7},
    {PCODE_F7_ALT, MOD_ALT, "Alt F7", GDK_F7},
    {PCODE_F8, MOD_NONE, "F8", GDK_F8},
    {PCODE_F8_SHIFT, MOD_SHIFT, "Shift F8", GDK_F8},
    {PCODE_F8_CTRL, MOD_CTRL, "Control F8", GDK_F8},
    {PCODE_F8_ALT, MOD_ALT, "Alt F8", GDK_F8},
    {PCODE_F9, MOD_NONE, "F9", GDK_F9},
    {PCODE_F9_SHIFT, MOD_SHIFT, "Shift F9", GDK_F9},
    {PCODE_F9_CTRL, MOD_CTRL, "Control F9", GDK_F9},
    {PCODE_F9_ALT, MOD_ALT, "Alt F9", GDK_F9},
    {PCODE_F10, MOD_NONE, "F10", GDK_F10},
    {PCODE_F10_SHIFT, MOD_SHIFT, "Shift F10", GDK_F10},
    {PCODE_F10_CTRL, MOD_CTRL, "Control F10", GDK_F10},
    {PCODE_F10_ALT, MOD_ALT, "Alt F10", GDK_F10},
    {PCODE_F11, MOD_NONE, "F11", GDK_F11},
    {PCODE_F11_SHIFT, MOD_SHIFT, "Shift F11", GDK_F11},
    {PCODE_F11_CTRL, MOD_CTRL, "Control F11", GDK_F11},
    {PCODE_F11_ALT, MOD_ALT, "Alt F11", GDK_F11},
    {PCODE_F12, MOD_NONE, "F12", GDK_F12},
    {PCODE_F12_SHIFT, MOD_SHIFT, "Shift F12", GDK_F12},
    {PCODE_F12_CTRL, MOD_CTRL, "Control F12", GDK_F12},
    {PCODE_F12_ALT, MOD_ALT, "Alt F12", GDK_F12},
    {PCODE_HOME_KP, MOD_NONE, "Keypad Home", GDK_KP_Home},
    {PCODE_HOME_KP_SHIFT, MOD_SHIFT, "Shift Keypad Home", GDK_KP_Home},
    {PCODE_HOME_KP_CTRL, MOD_CTRL, "Control Keypad Home", GDK_KP_Home},
    {PCODE_UP_ARROW_KP, MOD_NONE, "Keypad Up Arrow", GDK_KP_Up},
    {PCODE_UP_ARROW_KP_SHIFT, MOD_SHIFT, "Shift Up Arrow", GDK_KP_Up},
    {PCODE_UP_ARROW_KP_CTRL, MOD_CTRL, "Control Up Arrow", GDK_KP_Up},
    {PCODE_PAGE_UP_KP, MOD_NONE, "Keypad Page Up", GDK_KP_Page_Up},
    {PCODE_PAGE_UP_KP_SHIFT, MOD_SHIFT, "Shift Keypad Page Up", GDK_KP_Page_Up},
    {PCODE_PAGE_UP_KP_CTRL, MOD_CTRL, "Control Keypad Page Up", GDK_KP_Page_Up},
    {PCODE_LEFT_ARROW_KP, MOD_NONE, "Keypad Left Arrow", GDK_KP_Left},
    {PCODE_LEFT_ARROW_KP_SHIFT, MOD_SHIFT, "Shift Keypad Left Arrow", GDK_KP_Left},
    {PCODE_LEFT_ARROW_KP_CTRL, MOD_CTRL, "Control Keypad Left Arrow", GDK_KP_Left},
    {PCODE_RIGHT_ARROW_KP, MOD_NONE, "Keypad Right Arrow", GDK_KP_Right},
    {PCODE_RIGHT_ARROW_KP_SHIFT, MOD_SHIFT, "Shift Keypad Right Arrow", GDK_KP_Right},
    {PCODE_RIGHT_ARROW_KP_CTRL, MOD_CTRL, "Control Keypad Right Arrow", GDK_KP_Right},
    {PCODE_END_KP, MOD_NONE, "Keypad End", GDK_KP_End},
    {PCODE_END_KP_SHIFT, MOD_SHIFT, "Shift Keypad End", GDK_KP_End},
    {PCODE_END_KP_CTRL, MOD_CTRL, "Control Keypad End", GDK_KP_End},
    {PCODE_DOWN_ARROW_KP, MOD_NONE, "Keypad Down Arrow", GDK_KP_Down},
    {PCODE_DOWN_ARROW_KP_SHIFT, MOD_SHIFT, "Shift Keypad Down Arrow", GDK_KP_Down},
    {PCODE_DOWN_ARROW_KP_CTRL, MOD_CTRL, "Control Keypad Down Arrow", GDK_KP_Down},
    {PCODE_PAGE_DOWN_KP, MOD_NONE, "Keypad Page Down", GDK_KP_Page_Down},
    {PCODE_PAGE_DOWN_KP_SHIFT, MOD_SHIFT, "Shift Keypad Page Down", GDK_KP_Page_Down},
    {PCODE_PAGE_DOWN_KP_CTRL, MOD_CTRL, "Control Keypad Page Down", GDK_KP_Page_Down},
    {PCODE_INSERT_KP, MOD_NONE, "Keypad Insert", GDK_KP_Insert},
    {PCODE_INSERT_KP_SHIFT, MOD_SHIFT, "Shift Keypad Insert", GDK_KP_Insert},
    {PCODE_INSERT_KP_CTRL, MOD_CTRL, "Control Keypad Insert", GDK_KP_Insert},
    {PCODE_DELETE_KP, MOD_NONE, "Keypad Delete", GDK_KP_Delete},
    {PCODE_DELETE_KP_SHIFT, MOD_SHIFT, "Shift Keypad Delete", GDK_KP_Delete},
    {PCODE_DELETE_KP_CTRL, MOD_CTRL, "Control Keypad Delete", GDK_KP_Delete},
    {PCODE_HOME, MOD_NONE, "Home", GDK_Home},
    {PCODE_HOME_SHIFT, MOD_SHIFT, "Shift Home", GDK_Home},
    {PCODE_HOME_CTRL, MOD_CTRL, "Control Home", GDK_Home},
    {PCODE_HOME_ALT, MOD_ALT, "Alt Home", GDK_Home},
    {PCODE_UP_ARROW, MOD_NONE, "Up Arrow", GDK_Up},
    {PCODE_UP_ARROW_SHIFT, MOD_SHIFT, "Shift Up Arrow", GDK_Up},
    {PCODE_UP_ARROW_CTRL, MOD_CTRL, "Control Up Arrow", GDK_Up},
    {PCODE_UP_ARROW_ALT, MOD_ALT, "Alt Up Arrow", GDK_Up},
    {PCODE_PAGE_UP, MOD_NONE, "Page Up", GDK_Page_Up},
    {PCODE_PAGE_UP_SHIFT, MOD_SHIFT, "Shift Page Up", GDK_Page_Up},
    {PCODE_PAGE_UP_CTRL, MOD_CTRL, "Control Page Up", GDK_Page_Up},
    {PCODE_PAGE_UP_ALT, MOD_ALT, "Alt Page Up", GDK_Page_Up},
    {PCODE_LEFT_ARROW, MOD_NONE, "Left Arrow", GDK_Left},
    {PCODE_LEFT_ARROW_SHIFT, MOD_SHIFT, "Shift Left Arrow", GDK_Left},
    {PCODE_LEFT_ARROW_CTRL, MOD_CTRL, "Control Left Arrow", GDK_Left},
    {PCODE_LEFT_ARROW_ALT, MOD_ALT, "Alt Left Arrow", GDK_Left},
    {PCODE_RIGHT_ARROW, MOD_NONE, "Right Arrow", GDK_Right},
    {PCODE_RIGHT_ARROW_SHIFT, MOD_SHIFT, "Shift Right Arrow", GDK_Right},
    {PCODE_RIGHT_ARROW_CTRL, MOD_CTRL, "Control Right Arrow", GDK_Right},
    {PCODE_RIGHT_ARROW_ALT, MOD_ALT, "Alt Right Arrow", GDK_Right},
    {PCODE_END, MOD_NONE, "End", GDK_End},
    {PCODE_END_SHIFT, MOD_SHIFT, "Shift End", GDK_End},
    {PCODE_END_CTRL, MOD_CTRL, "Control End", GDK_End},
    {PCODE_END_ALT, MOD_ALT, "Alt End", GDK_End},
    {PCODE_DOWN_ARROW, MOD_NONE, "Down Arrow", GDK_Down},
    {PCODE_DOWN_ARROW_SHIFT, MOD_SHIFT, "Shift Down Arrow", GDK_Down},
    {PCODE_DOWN_ARROW_CTRL, MOD_CTRL, "Control Down Arrow", GDK_Down},
    {PCODE_DOWN_ARROW_ALT, MOD_ALT, "Alt Down Arrow", GDK_Down},
    {PCODE_PAGE_DOWN, MOD_NONE, "Page Down", GDK_Page_Down},
    {PCODE_PAGE_DOWN_SHIFT, MOD_SHIFT, "Shift Page Down", GDK_Page_Down},
    {PCODE_PAGE_DOWN_CTRL, MOD_CTRL, "Control Page Down", GDK_Page_Down},
    {PCODE_PAGE_DOWN_ALT, MOD_ALT, "Alt Page Down", GDK_Page_Down},
    {PCODE_INSERT, MOD_NONE, "Insert", GDK_Insert},
    {PCODE_INSERT_SHIFT, MOD_SHIFT, "Shift Insert", GDK_Insert},
    {PCODE_INSERT_CTRL, MOD_CTRL, "Control Insert", GDK_Insert},
    {PCODE_INSERT_ALT, MOD_ALT, "Alt Insert", GDK_Insert},
    {PCODE_DELETE, MOD_NONE, "Delete", GDK_Delete},
    {PCODE_DELETE_SHIFT, MOD_SHIFT, "Shift Delete", GDK_Delete},
    {PCODE_DELETE_CTRL, MOD_CTRL, "Control Delete", GDK_Delete},
    {PCODE_DELETE_ALT, MOD_ALT, "Alt Delete", GDK_Delete},
    {PCODE_PRINT_SCREEN_CTRL, MOD_NONE, "Print Screen", GDK_Print},
    {PCODE_PAUSE_BREAK_CTRL, MOD_NONE, "Pause/Break", GDK_Pause},
    {PCODE_BACKSPACE, MOD_NONE, "Backspace", GDK_BackSpace},
    {PCODE_BACKSPACE_SHIFT, MOD_SHIFT, "Shift Backspace", GDK_BackSpace},
    {PCODE_BACKSPACE_CTRL, MOD_CTRL, "Control Backspace", GDK_BackSpace},
    {PCODE_ENTER, MOD_NONE, "Enter", GDK_Return},
    {PCODE_ENTER_CTRL, MOD_CTRL, "Control Enter", GDK_Return},
    {PCODE_TAB, MOD_NONE, "Tab", GDK_Tab},
    {PCODE_TAB_SHIFT, MOD_SHIFT, "Shift Tab", GDK_Tab},
    {PCODE_TAB_CTRL, MOD_CTRL, "Control Tab", GDK_Tab},
    {PCODE_TAB_ALT, MOD_ALT, "Alt Tab", GDK_Tab},
    {PCODE_A, MOD_NONE, "a", GDK_a},
    {PCODE_A_SHIFT, MOD_SHIFT, "Shift a", GDK_a},
    {PCODE_A_CTRL, MOD_CTRL, "Control a", GDK_a},
    {PCODE_A_ALT, MOD_ALT, "Alt a", GDK_a},
    {PCODE_B, MOD_NONE, "b", GDK_b},
    {PCODE_B_SHIFT, MOD_SHIFT, "Shift b", GDK_b},
    {PCODE_B_CTRL, MOD_CTRL, "Control b", GDK_b},
    {PCODE_B_ALT, MOD_ALT, "Alt b", GDK_b},
    {PCODE_C, MOD_NONE, "c", GDK_c},
    {PCODE_C_SHIFT, MOD_SHIFT, "Shift c", GDK_c},
    {PCODE_C_CTRL, MOD_CTRL, "Control c", GDK_c},
    {PCODE_C_ALT, MOD_ALT, "Alt c", GDK_c},
    {PCODE_D, MOD_NONE, "d", GDK_d},
    {PCODE_D_SHIFT, MOD_SHIFT, "Shift d", GDK_d},
    {PCODE_D_CTRL, MOD_CTRL, "Control d", GDK_d},
    {PCODE_D_ALT, MOD_ALT, "Alt d", GDK_d},
    {PCODE_E, MOD_NONE, "e", GDK_e},
    {PCODE_E_SHIFT, MOD_SHIFT, "Shift e", GDK_e},
    {PCODE_E_CTRL, MOD_CTRL, "Control e", GDK_e},
    {PCODE_E_ALT, MOD_ALT, "Alt e", GDK_e},
    {PCODE_F, MOD_NONE, "f", GDK_f},
    {PCODE_F_SHIFT, MOD_SHIFT, "Shift f", GDK_f},
    {PCODE_F_CTRL, MOD_CTRL, "Control f", GDK_f},
    {PCODE_F_ALT, MOD_ALT, "Alt f", GDK_f},
    {PCODE_G, MOD_NONE, "g", GDK_g},
    {PCODE_G_SHIFT, MOD_SHIFT, "Shift g", GDK_g},
    {PCODE_G_CTRL, MOD_CTRL, "Control g", GDK_g},
    {PCODE_G_ALT, MOD_ALT, "Alt g", GDK_g},
    {PCODE_H, MOD_NONE, "h", GDK_h},
    {PCODE_H_SHIFT, MOD_SHIFT, "Shift h", GDK_h},
    {PCODE_H_CTRL, MOD_CTRL, "Control h", GDK_h},
    {PCODE_H_ALT, MOD_ALT, "Alt h", GDK_h},
    {PCODE_I, MOD_NONE, "i", GDK_i},
    {PCODE_I_SHIFT, MOD_SHIFT, "Shift i", GDK_i},
    {PCODE_I_CTRL, MOD_CTRL, "Control i", GDK_i},
    {PCODE_I_ALT, MOD_ALT, "Alt i", GDK_i},
    {PCODE_J, MOD_NONE, "j", GDK_j},
    {PCODE_J_SHIFT, MOD_SHIFT, "Shift j", GDK_j},
    {PCODE_J_CTRL, MOD_CTRL, "Control j", GDK_j},
    {PCODE_J_ALT, MOD_ALT, "Alt j", GDK_j},
    {PCODE_K, MOD_NONE, "k", GDK_k},
    {PCODE_K_SHIFT, MOD_SHIFT, "Shift k", GDK_k},
    {PCODE_K_CTRL, MOD_CTRL, "Control k", GDK_k},
    {PCODE_K_ALT, MOD_ALT, "Alt k", GDK_k},
    {PCODE_L, MOD_NONE, "l", GDK_l},
    {PCODE_L_SHIFT, MOD_SHIFT, "Shift l", GDK_l},
    {PCODE_L_CTRL, MOD_CTRL, "Control l", GDK_l},
    {PCODE_L_ALT, MOD_ALT, "Alt l", GDK_l},
    {PCODE_M, MOD_NONE, "m", GDK_m},
    {PCODE_M_SHIFT, MOD_SHIFT, "Shift m", GDK_m},
    {PCODE_M_CTRL, MOD_CTRL, "Control m", GDK_m},
    {PCODE_M_ALT, MOD_ALT, "Alt m", GDK_m},
    {PCODE_N, MOD_NONE, "n", GDK_n},
    {PCODE_N_SHIFT, MOD_SHIFT, "Shift n", GDK_n},
    {PCODE_N_CTRL, MOD_CTRL, "Control n", GDK_n},
    {PCODE_N_ALT, MOD_ALT, "Alt n", GDK_n},
    {PCODE_O, MOD_NONE, "o", GDK_o},
    {PCODE_O_SHIFT, MOD_SHIFT, "Shift o", GDK_o},
    {PCODE_O_CTRL, MOD_CTRL, "Control o", GDK_o},
    {PCODE_O_ALT, MOD_ALT, "Alt o", GDK_o},
    {PCODE_P, MOD_NONE, "p", GDK_p},
    {PCODE_P_SHIFT, MOD_SHIFT, "Shift p", GDK_p},
    {PCODE_P_CTRL, MOD_CTRL, "Control p", GDK_p},
    {PCODE_P_ALT, MOD_ALT, "Alt p", GDK_p},
    {PCODE_Q, MOD_NONE, "q", GDK_q},
    {PCODE_Q_SHIFT, MOD_SHIFT, "Shift q", GDK_q},
    {PCODE_Q_CTRL, MOD_CTRL, "Control q", GDK_q},
    {PCODE_Q_ALT, MOD_ALT, "Alt q", GDK_q},
    {PCODE_R, MOD_NONE, "r", GDK_r},
    {PCODE_R_SHIFT, MOD_SHIFT, "Shift r", GDK_r},
    {PCODE_R_CTRL, MOD_CTRL, "Control r", GDK_r},
    {PCODE_R_ALT, MOD_ALT, "Alt r", GDK_r},
    {PCODE_S, MOD_NONE, "s", GDK_s},
    {PCODE_S_SHIFT, MOD_SHIFT, "Shift s", GDK_s},
    {PCODE_S_CTRL, MOD_CTRL, "Control s", GDK_s},
    {PCODE_S_ALT, MOD_ALT, "Alt s", GDK_s},
    {PCODE_T, MOD_NONE, "t", GDK_t},
    {PCODE_T_SHIFT, MOD_SHIFT, "Shift t", GDK_t},
    {PCODE_T_CTRL, MOD_CTRL, "Control t", GDK_t},
    {PCODE_T_ALT, MOD_ALT, "Alt t", GDK_t},
    {PCODE_U, MOD_NONE, "u", GDK_u},
    {PCODE_U_SHIFT, MOD_SHIFT, "Shift u", GDK_u},
    {PCODE_U_CTRL, MOD_CTRL, "Control u", GDK_u},
    {PCODE_U_ALT, MOD_ALT, "Alt u", GDK_u},
    {PCODE_V, MOD_NONE, "v", GDK_v},
    {PCODE_V_SHIFT, MOD_SHIFT, "Shift v", GDK_v},
    {PCODE_V_CTRL, MOD_CTRL, "Control v", GDK_v},
    {PCODE_V_ALT, MOD_ALT, "Alt v", GDK_v},
    {PCODE_W, MOD_NONE, "w", GDK_w},
    {PCODE_W_SHIFT, MOD_SHIFT, "Shift w", GDK_w},
    {PCODE_W_CTRL, MOD_CTRL, "Control w", GDK_w},
    {PCODE_W_ALT, MOD_ALT, "Alt w", GDK_w},
    {PCODE_X, MOD_NONE, "x", GDK_x},
    {PCODE_X_SHIFT, MOD_SHIFT, "Shift x", GDK_x},
    {PCODE_X_CTRL, MOD_CTRL, "Control x", GDK_x},
    {PCODE_X_ALT, MOD_ALT, "Alt x", GDK_x},
    {PCODE_Y, MOD_NONE, "y", GDK_y},
    {PCODE_Y_SHIFT, MOD_SHIFT, "Shift y", GDK_y},
    {PCODE_Y_CTRL, MOD_CTRL, "Control y", GDK_y},
    {PCODE_Y_ALT, MOD_ALT, "Alt y", GDK_y},
    {PCODE_Z, MOD_NONE, "z", GDK_z},
    {PCODE_Z_SHIFT, MOD_SHIFT, "Shift z", GDK_z},
    {PCODE_Z_CTRL, MOD_CTRL, "Control z", GDK_z},
    {PCODE_Z_ALT, MOD_ALT, "Alt z", GDK_z},
    {PCODE_1, MOD_NONE, "1", GDK_1},
    {PCODE_1_SHIFT, MOD_SHIFT, "Shift 1", GDK_1},
    {PCODE_1_ALT, MOD_ALT, "Alt 1", GDK_1},
    {PCODE_2, MOD_NONE, "2", GDK_2},
    {PCODE_2_SHIFT, MOD_SHIFT, "Shift 2", GDK_2},
    {PCODE_2_ALT, MOD_ALT, "Alt 2", GDK_2},
    {PCODE_3, MOD_NONE, "3", GDK_3},
    {PCODE_3_SHIFT, MOD_SHIFT, "Shift 3", GDK_3},
    {PCODE_3_ALT, MOD_ALT, "Alt 3", GDK_3},
    {PCODE_4, MOD_NONE, "4", GDK_4},
    {PCODE_4_SHIFT, MOD_SHIFT, "Shift 4", GDK_4},
    {PCODE_4_ALT, MOD_ALT, "Alt 4", GDK_4},
    {PCODE_5, MOD_NONE, "5", GDK_5},
    {PCODE_5_SHIFT, MOD_SHIFT, "Shift 5", GDK_5},
    {PCODE_5_ALT, MOD_ALT, "Alt 5", GDK_5},
    {PCODE_6, MOD_NONE, "6", GDK_6},
    {PCODE_6_SHIFT, MOD_SHIFT, "Shift 6", GDK_6},
    {PCODE_6_CTRL, MOD_CTRL, "Control 6", GDK_6},
    {PCODE_6_ALT, MOD_ALT, "Alt 6", GDK_6},
    {PCODE_7, MOD_NONE, "7", GDK_7},
    {PCODE_7_SHIFT, MOD_SHIFT, "Shift 7", GDK_7},
    {PCODE_7_ALT, MOD_ALT, "Alt 7", GDK_7},
    {PCODE_8, MOD_NONE, "8", GDK_8},
    {PCODE_8_SHIFT, MOD_SHIFT, "Shift 8", GDK_8},
    {PCODE_8_ALT, MOD_ALT, "Alt 8", GDK_8},
    {PCODE_9, MOD_NONE, "9", GDK_9},
    {PCODE_9_SHIFT, MOD_SHIFT, "Shift 9", GDK_9},
    {PCODE_9_ALT, MOD_ALT, "Alt 9", GDK_9},
    {PCODE_0, MOD_NONE, "0", GDK_0},
    {PCODE_0_SHIFT, MOD_SHIFT, "Shift 0", GDK_0},
    {PCODE_0_ALT, MOD_ALT, "Alt 0", GDK_0},
    {PCODE_MINUS, MOD_NONE, "Minus", GDK_minus},
    {PCODE_MINUS_SHIFT, MOD_SHIFT, "Shift Minus", GDK_minus},
    {PCODE_MINUS_CTRL, MOD_CTRL, "Control Minus", GDK_minus},
    {PCODE_MINUS_ALT, MOD_ALT, "Alt Minus", GDK_minus},
    {PCODE_EQUALS, MOD_NONE, "Equal", GDK_equal},
    {PCODE_EQUALS_SHIFT, MOD_SHIFT, "Shift Equal", GDK_equal},
    {PCODE_EQUALS_ALT, MOD_ALT, "Alt Equal", GDK_equal},
    {PCODE_SPACE, MOD_NONE, "Space", GDK_space},
    {PCODE_SPACE_SHIFT, MOD_SHIFT, "Shift Space", GDK_space},
    {PCODE_SPACE_CTRL, MOD_CTRL, "Control Space", GDK_space},
    {PCODE_SPACE_ALT, MOD_ALT, "Alt Space", GDK_space},
    {PCODE_SEMICOLON, MOD_NONE, "Semicolon", GDK_semicolon},
    {PCODE_SEMICOLON_SHIFT, MOD_SHIFT, "Shift Semicolon", GDK_semicolon},
    {PCODE_SEMICOLON_ALT, MOD_ALT, "Alt Semicolon", GDK_semicolon},
    {PCODE_COMMA, MOD_NONE, "Comma", GDK_comma},
    {PCODE_COMMA_SHIFT, MOD_SHIFT, "Shift Comma", GDK_comma},
    {PCODE_COMMA_ALT, MOD_ALT, "Alt Comma", GDK_comma},
    {PCODE_PERIOD, MOD_NONE, "Period", GDK_period},
    {PCODE_PERIOD_SHIFT, MOD_SHIFT, "Shift Period", GDK_period},
    {PCODE_PERIOD_ALT, MOD_ALT, "Alt Period", GDK_period},
    {PCODE_SLASH, MOD_NONE, "Slash", GDK_slash},
    {PCODE_SLASH_SHIFT, MOD_SHIFT, "Shift Slash", GDK_slash},
    {PCODE_SLASH_ALT, MOD_ALT, "Alt Slash", GDK_slash},
    {PCODE_ENTER_KP, MOD_NONE, "Keypad Enter", GDK_KP_Enter},
    {PCODE_ENTER_KP_CTRL, MOD_CTRL, "Control Keypad Enter", GDK_KP_Enter},
    {PCODE_ENTER_KP_ALT, MOD_ALT, "Alt Keypad Enter", GDK_KP_Enter},
    {PCODE_SLASH_KP, MOD_NONE, "Keypad Divide", GDK_KP_Divide},
    {PCODE_SLASH_KP_SHIFT, MOD_SHIFT, "Shift Keypad Divide", GDK_KP_Divide},
    {PCODE_SLASH_KP_CTRL, MOD_CTRL, "Control Keypad Divide", GDK_KP_Divide},
    {PCODE_SLASH_KP_ALT, MOD_ALT, "Alt Keypad Divide", GDK_KP_Divide},
    {PCODE_MULT_KP, MOD_NONE, "Keypad Multiply", GDK_KP_Multiply},
    {PCODE_MULT_KP_SHIFT, MOD_SHIFT, "Shift Keypad Multiply", GDK_KP_Multiply},
    {PCODE_MULT_KP_CTRL, MOD_CTRL, "Control Keypad Multiply", GDK_KP_Multiply},
    {PCODE_SUB_KP, MOD_NONE, "Keypad Subtract", GDK_KP_Subtract},
    {PCODE_SUB_KP_SHIFT, MOD_SHIFT, "Shift Keypad Subtract", GDK_KP_Subtract},
    {PCODE_SUB_KP_CTRL, MOD_CTRL, "Control Keypad Subtract", GDK_KP_Subtract},
    {PCODE_SUB_KP_ALT, MOD_ALT, "Alt Keypad Subtract", GDK_KP_Subtract},
    {PCODE_ADD_KP, MOD_NONE, "Keypad Add", GDK_KP_Add},
    {PCODE_ADD_KP_SHIFT, MOD_SHIFT, "Shift Keypad Add", GDK_KP_Add},
    {PCODE_ADD_KP_CTRL, MOD_CTRL, "Control Keypad Add", GDK_KP_Add},
    {PCODE_ADD_KP_ALT, MOD_ALT, "Alt Keypad Add", GDK_KP_Add},
    {PCODE_5_KP, MOD_NONE, "Keypad 5", GDK_KP_5},
    {PCODE_5_KP_SHIFT, MOD_SHIFT, "Shift Keypad 5", GDK_KP_5},
    {PCODE_5_KP_CTRL, MOD_CTRL, "Control Keypad 5", GDK_KP_5},
};
